version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: sidekiq
    versions:
    - 5.2.4
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.8.1
    - 1.9.0
    - 1.9.1
  - dependency-name: sidekiq
    versions:
    - 6.1.3
    - 6.2.0
  - dependency-name: country_select
    versions:
    - 5.0.0
  - dependency-name: paper_trail
    versions:
    - 11.1.0
  - dependency-name: rails_admin
    versions:
    - 2.0.2
    - 2.1.0
  - dependency-name: breadcrumbs_on_rails
    versions:
    - 4.0.0
  - dependency-name: newrelic_rpm
    versions:
    - 6.15.0
  - dependency-name: acts_as_list
    versions:
    - 1.0.3
