language: ruby
bundler_args: --without development
rvm:
  - 2.1.2
script: bundle exec rspec spec
before_script:
  - cp config/database.yml.template config/database.yml
  - cp config/secrets.yml.template config/secrets.yml
  - psql -c 'create database app_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:schema:load
